version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iotgo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - iotgo-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - RUNMODE=prod
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=iotgo
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - iotgo-network

  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    environment:
      - API_URL=http://backend:8080
      - AUTH_URL=http://backend:8080
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - iotgo-network

volumes:
  postgres-data:

networks:
  iotgo-network:
    driver: bridge
