version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=iotnew
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_SSLMODE=disable
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - iotgo-network

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=iotnew
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - iotgo-network

volumes:
  postgres-data:
    driver: local

networks:
  iotgo-network:
    driver: bridge