// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	DataSink        *dataSink
	DataSource      *dataSource
	Device          *device
	SensorData      *sensorData
	User            *user
	UserInteraction *userInteraction
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	DataSink = &Q.DataSink
	DataSource = &Q.DataSource
	Device = &Q.Device
	SensorData = &Q.SensorData
	User = &Q.User
	UserInteraction = &Q.UserInteraction
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		DataSink:        newDataSink(db, opts...),
		DataSource:      newDataSource(db, opts...),
		Device:          newDevice(db, opts...),
		SensorData:      newSensorData(db, opts...),
		User:            newUser(db, opts...),
		UserInteraction: newUserInteraction(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	DataSink        dataSink
	DataSource      dataSource
	Device          device
	SensorData      sensorData
	User            user
	UserInteraction userInteraction
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		DataSink:        q.DataSink.clone(db),
		DataSource:      q.DataSource.clone(db),
		Device:          q.Device.clone(db),
		SensorData:      q.SensorData.clone(db),
		User:            q.User.clone(db),
		UserInteraction: q.UserInteraction.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		DataSink:        q.DataSink.replaceDB(db),
		DataSource:      q.DataSource.replaceDB(db),
		Device:          q.Device.replaceDB(db),
		SensorData:      q.SensorData.replaceDB(db),
		User:            q.User.replaceDB(db),
		UserInteraction: q.UserInteraction.replaceDB(db),
	}
}

type queryCtx struct {
	DataSink        IDataSinkDo
	DataSource      IDataSourceDo
	Device          IDeviceDo
	SensorData      ISensorDataDo
	User            IUserDo
	UserInteraction IUserInteractionDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		DataSink:        q.DataSink.WithContext(ctx),
		DataSource:      q.DataSource.WithContext(ctx),
		Device:          q.Device.WithContext(ctx),
		SensorData:      q.SensorData.WithContext(ctx),
		User:            q.User.WithContext(ctx),
		UserInteraction: q.UserInteraction.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
