// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newUserInteraction(db *gorm.DB, opts ...gen.DOOption) userInteraction {
	_userInteraction := userInteraction{}

	_userInteraction.userInteractionDo.UseDB(db, opts...)
	_userInteraction.userInteractionDo.UseModel(&model.UserInteraction{})

	tableName := _userInteraction.userInteractionDo.TableName()
	_userInteraction.ALL = field.NewAsterisk(tableName)
	_userInteraction.ID = field.NewUint(tableName, "id")
	_userInteraction.CreatedAt = field.NewTime(tableName, "created_at")
	_userInteraction.UpdatedAt = field.NewTime(tableName, "updated_at")
	_userInteraction.DeletedAt = field.NewField(tableName, "deleted_at")
	_userInteraction.UserID = field.NewUint(tableName, "user_id")
	_userInteraction.DeviceID = field.NewUint(tableName, "device_id")
	_userInteraction.SourceID = field.NewUint(tableName, "source_id")
	_userInteraction.SinkID = field.NewUint(tableName, "sink_id")
	_userInteraction.Action = field.NewString(tableName, "action")
	_userInteraction.Timestamp = field.NewTime(tableName, "timestamp")
	_userInteraction.Device = userInteractionBelongsToDevice{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Device", "model.Device"),
	}

	_userInteraction.DataSource = userInteractionBelongsToDataSource{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("DataSource", "model.DataSource"),
	}

	_userInteraction.DataSink = userInteractionBelongsToDataSink{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("DataSink", "model.DataSink"),
	}

	_userInteraction.fillFieldMap()

	return _userInteraction
}

type userInteraction struct {
	userInteractionDo userInteractionDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	UserID    field.Uint
	DeviceID  field.Uint
	SourceID  field.Uint
	SinkID    field.Uint
	Action    field.String
	Timestamp field.Time
	Device    userInteractionBelongsToDevice

	DataSource userInteractionBelongsToDataSource

	DataSink userInteractionBelongsToDataSink

	fieldMap map[string]field.Expr
}

func (u userInteraction) Table(newTableName string) *userInteraction {
	u.userInteractionDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userInteraction) As(alias string) *userInteraction {
	u.userInteractionDo.DO = *(u.userInteractionDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userInteraction) updateTableName(table string) *userInteraction {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewUint(table, "id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.DeletedAt = field.NewField(table, "deleted_at")
	u.UserID = field.NewUint(table, "user_id")
	u.DeviceID = field.NewUint(table, "device_id")
	u.SourceID = field.NewUint(table, "source_id")
	u.SinkID = field.NewUint(table, "sink_id")
	u.Action = field.NewString(table, "action")
	u.Timestamp = field.NewTime(table, "timestamp")

	u.fillFieldMap()

	return u
}

func (u *userInteraction) WithContext(ctx context.Context) IUserInteractionDo {
	return u.userInteractionDo.WithContext(ctx)
}

func (u userInteraction) TableName() string { return u.userInteractionDo.TableName() }

func (u userInteraction) Alias() string { return u.userInteractionDo.Alias() }

func (u userInteraction) Columns(cols ...field.Expr) gen.Columns {
	return u.userInteractionDo.Columns(cols...)
}

func (u *userInteraction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userInteraction) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 13)
	u.fieldMap["id"] = u.ID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["device_id"] = u.DeviceID
	u.fieldMap["source_id"] = u.SourceID
	u.fieldMap["sink_id"] = u.SinkID
	u.fieldMap["action"] = u.Action
	u.fieldMap["timestamp"] = u.Timestamp

}

func (u userInteraction) clone(db *gorm.DB) userInteraction {
	u.userInteractionDo.ReplaceConnPool(db.Statement.ConnPool)
	u.Device.db = db.Session(&gorm.Session{Initialized: true})
	u.Device.db.Statement.ConnPool = db.Statement.ConnPool
	u.DataSource.db = db.Session(&gorm.Session{Initialized: true})
	u.DataSource.db.Statement.ConnPool = db.Statement.ConnPool
	u.DataSink.db = db.Session(&gorm.Session{Initialized: true})
	u.DataSink.db.Statement.ConnPool = db.Statement.ConnPool
	return u
}

func (u userInteraction) replaceDB(db *gorm.DB) userInteraction {
	u.userInteractionDo.ReplaceDB(db)
	u.Device.db = db.Session(&gorm.Session{})
	u.DataSource.db = db.Session(&gorm.Session{})
	u.DataSink.db = db.Session(&gorm.Session{})
	return u
}

type userInteractionBelongsToDevice struct {
	db *gorm.DB

	field.RelationField
}

func (a userInteractionBelongsToDevice) Where(conds ...field.Expr) *userInteractionBelongsToDevice {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userInteractionBelongsToDevice) WithContext(ctx context.Context) *userInteractionBelongsToDevice {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userInteractionBelongsToDevice) Session(session *gorm.Session) *userInteractionBelongsToDevice {
	a.db = a.db.Session(session)
	return &a
}

func (a userInteractionBelongsToDevice) Model(m *model.UserInteraction) *userInteractionBelongsToDeviceTx {
	return &userInteractionBelongsToDeviceTx{a.db.Model(m).Association(a.Name())}
}

func (a userInteractionBelongsToDevice) Unscoped() *userInteractionBelongsToDevice {
	a.db = a.db.Unscoped()
	return &a
}

type userInteractionBelongsToDeviceTx struct{ tx *gorm.Association }

func (a userInteractionBelongsToDeviceTx) Find() (result *model.Device, err error) {
	return result, a.tx.Find(&result)
}

func (a userInteractionBelongsToDeviceTx) Append(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userInteractionBelongsToDeviceTx) Replace(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userInteractionBelongsToDeviceTx) Delete(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userInteractionBelongsToDeviceTx) Clear() error {
	return a.tx.Clear()
}

func (a userInteractionBelongsToDeviceTx) Count() int64 {
	return a.tx.Count()
}

func (a userInteractionBelongsToDeviceTx) Unscoped() *userInteractionBelongsToDeviceTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userInteractionBelongsToDataSource struct {
	db *gorm.DB

	field.RelationField
}

func (a userInteractionBelongsToDataSource) Where(conds ...field.Expr) *userInteractionBelongsToDataSource {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userInteractionBelongsToDataSource) WithContext(ctx context.Context) *userInteractionBelongsToDataSource {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userInteractionBelongsToDataSource) Session(session *gorm.Session) *userInteractionBelongsToDataSource {
	a.db = a.db.Session(session)
	return &a
}

func (a userInteractionBelongsToDataSource) Model(m *model.UserInteraction) *userInteractionBelongsToDataSourceTx {
	return &userInteractionBelongsToDataSourceTx{a.db.Model(m).Association(a.Name())}
}

func (a userInteractionBelongsToDataSource) Unscoped() *userInteractionBelongsToDataSource {
	a.db = a.db.Unscoped()
	return &a
}

type userInteractionBelongsToDataSourceTx struct{ tx *gorm.Association }

func (a userInteractionBelongsToDataSourceTx) Find() (result *model.DataSource, err error) {
	return result, a.tx.Find(&result)
}

func (a userInteractionBelongsToDataSourceTx) Append(values ...*model.DataSource) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userInteractionBelongsToDataSourceTx) Replace(values ...*model.DataSource) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userInteractionBelongsToDataSourceTx) Delete(values ...*model.DataSource) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userInteractionBelongsToDataSourceTx) Clear() error {
	return a.tx.Clear()
}

func (a userInteractionBelongsToDataSourceTx) Count() int64 {
	return a.tx.Count()
}

func (a userInteractionBelongsToDataSourceTx) Unscoped() *userInteractionBelongsToDataSourceTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userInteractionBelongsToDataSink struct {
	db *gorm.DB

	field.RelationField
}

func (a userInteractionBelongsToDataSink) Where(conds ...field.Expr) *userInteractionBelongsToDataSink {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userInteractionBelongsToDataSink) WithContext(ctx context.Context) *userInteractionBelongsToDataSink {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userInteractionBelongsToDataSink) Session(session *gorm.Session) *userInteractionBelongsToDataSink {
	a.db = a.db.Session(session)
	return &a
}

func (a userInteractionBelongsToDataSink) Model(m *model.UserInteraction) *userInteractionBelongsToDataSinkTx {
	return &userInteractionBelongsToDataSinkTx{a.db.Model(m).Association(a.Name())}
}

func (a userInteractionBelongsToDataSink) Unscoped() *userInteractionBelongsToDataSink {
	a.db = a.db.Unscoped()
	return &a
}

type userInteractionBelongsToDataSinkTx struct{ tx *gorm.Association }

func (a userInteractionBelongsToDataSinkTx) Find() (result *model.DataSink, err error) {
	return result, a.tx.Find(&result)
}

func (a userInteractionBelongsToDataSinkTx) Append(values ...*model.DataSink) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userInteractionBelongsToDataSinkTx) Replace(values ...*model.DataSink) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userInteractionBelongsToDataSinkTx) Delete(values ...*model.DataSink) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userInteractionBelongsToDataSinkTx) Clear() error {
	return a.tx.Clear()
}

func (a userInteractionBelongsToDataSinkTx) Count() int64 {
	return a.tx.Count()
}

func (a userInteractionBelongsToDataSinkTx) Unscoped() *userInteractionBelongsToDataSinkTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userInteractionDo struct{ gen.DO }

type IUserInteractionDo interface {
	gen.SubQuery
	Debug() IUserInteractionDo
	WithContext(ctx context.Context) IUserInteractionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserInteractionDo
	WriteDB() IUserInteractionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserInteractionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserInteractionDo
	Not(conds ...gen.Condition) IUserInteractionDo
	Or(conds ...gen.Condition) IUserInteractionDo
	Select(conds ...field.Expr) IUserInteractionDo
	Where(conds ...gen.Condition) IUserInteractionDo
	Order(conds ...field.Expr) IUserInteractionDo
	Distinct(cols ...field.Expr) IUserInteractionDo
	Omit(cols ...field.Expr) IUserInteractionDo
	Join(table schema.Tabler, on ...field.Expr) IUserInteractionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserInteractionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserInteractionDo
	Group(cols ...field.Expr) IUserInteractionDo
	Having(conds ...gen.Condition) IUserInteractionDo
	Limit(limit int) IUserInteractionDo
	Offset(offset int) IUserInteractionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserInteractionDo
	Unscoped() IUserInteractionDo
	Create(values ...*model.UserInteraction) error
	CreateInBatches(values []*model.UserInteraction, batchSize int) error
	Save(values ...*model.UserInteraction) error
	First() (*model.UserInteraction, error)
	Take() (*model.UserInteraction, error)
	Last() (*model.UserInteraction, error)
	Find() ([]*model.UserInteraction, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserInteraction, err error)
	FindInBatches(result *[]*model.UserInteraction, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserInteraction) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserInteractionDo
	Assign(attrs ...field.AssignExpr) IUserInteractionDo
	Joins(fields ...field.RelationField) IUserInteractionDo
	Preload(fields ...field.RelationField) IUserInteractionDo
	FirstOrInit() (*model.UserInteraction, error)
	FirstOrCreate() (*model.UserInteraction, error)
	FindByPage(offset int, limit int) (result []*model.UserInteraction, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserInteractionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	FilterWithNameAndRole(name string, role string) (result []model.UserInteraction, err error)
	GetByID(id int) (result model.UserInteraction, err error)
	GetByRoles(rolesName []string) (result []*model.UserInteraction, err error)
}

// SELECT * FROM @@table WHERE name = @name{{if role !=""}} AND role = @role{{end}}
func (u userInteractionDo) FilterWithNameAndRole(name string, role string) (result []model.UserInteraction, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	generateSQL.WriteString("SELECT * FROM user_interactions WHERE name = ? ")
	if role != "" {
		params = append(params, role)
		generateSQL.WriteString("AND role = ? ")
	}

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// SELECT * FROM @@table WHERE id=@id
func (u userInteractionDo) GetByID(id int) (result model.UserInteraction, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM user_interactions WHERE id=? ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// SELECT * FROM @@table WHERE role IN @rolesName
func (u userInteractionDo) GetByRoles(rolesName []string) (result []*model.UserInteraction, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, rolesName)
	generateSQL.WriteString("SELECT * FROM user_interactions WHERE role IN ? ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (u userInteractionDo) Debug() IUserInteractionDo {
	return u.withDO(u.DO.Debug())
}

func (u userInteractionDo) WithContext(ctx context.Context) IUserInteractionDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userInteractionDo) ReadDB() IUserInteractionDo {
	return u.Clauses(dbresolver.Read)
}

func (u userInteractionDo) WriteDB() IUserInteractionDo {
	return u.Clauses(dbresolver.Write)
}

func (u userInteractionDo) Session(config *gorm.Session) IUserInteractionDo {
	return u.withDO(u.DO.Session(config))
}

func (u userInteractionDo) Clauses(conds ...clause.Expression) IUserInteractionDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userInteractionDo) Returning(value interface{}, columns ...string) IUserInteractionDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userInteractionDo) Not(conds ...gen.Condition) IUserInteractionDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userInteractionDo) Or(conds ...gen.Condition) IUserInteractionDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userInteractionDo) Select(conds ...field.Expr) IUserInteractionDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userInteractionDo) Where(conds ...gen.Condition) IUserInteractionDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userInteractionDo) Order(conds ...field.Expr) IUserInteractionDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userInteractionDo) Distinct(cols ...field.Expr) IUserInteractionDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userInteractionDo) Omit(cols ...field.Expr) IUserInteractionDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userInteractionDo) Join(table schema.Tabler, on ...field.Expr) IUserInteractionDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userInteractionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserInteractionDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userInteractionDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserInteractionDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userInteractionDo) Group(cols ...field.Expr) IUserInteractionDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userInteractionDo) Having(conds ...gen.Condition) IUserInteractionDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userInteractionDo) Limit(limit int) IUserInteractionDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userInteractionDo) Offset(offset int) IUserInteractionDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userInteractionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserInteractionDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userInteractionDo) Unscoped() IUserInteractionDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userInteractionDo) Create(values ...*model.UserInteraction) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userInteractionDo) CreateInBatches(values []*model.UserInteraction, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userInteractionDo) Save(values ...*model.UserInteraction) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userInteractionDo) First() (*model.UserInteraction, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserInteraction), nil
	}
}

func (u userInteractionDo) Take() (*model.UserInteraction, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserInteraction), nil
	}
}

func (u userInteractionDo) Last() (*model.UserInteraction, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserInteraction), nil
	}
}

func (u userInteractionDo) Find() ([]*model.UserInteraction, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserInteraction), err
}

func (u userInteractionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserInteraction, err error) {
	buf := make([]*model.UserInteraction, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userInteractionDo) FindInBatches(result *[]*model.UserInteraction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userInteractionDo) Attrs(attrs ...field.AssignExpr) IUserInteractionDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userInteractionDo) Assign(attrs ...field.AssignExpr) IUserInteractionDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userInteractionDo) Joins(fields ...field.RelationField) IUserInteractionDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userInteractionDo) Preload(fields ...field.RelationField) IUserInteractionDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userInteractionDo) FirstOrInit() (*model.UserInteraction, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserInteraction), nil
	}
}

func (u userInteractionDo) FirstOrCreate() (*model.UserInteraction, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserInteraction), nil
	}
}

func (u userInteractionDo) FindByPage(offset int, limit int) (result []*model.UserInteraction, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userInteractionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userInteractionDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userInteractionDo) Delete(models ...*model.UserInteraction) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userInteractionDo) withDO(do gen.Dao) *userInteractionDo {
	u.DO = *do.(*gen.DO)
	return u
}
