name: Build and Push Docker Images to Artifactory

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

env:
  # Replace with your JFrog Artifactory Registry Host
  # Example: your-artifactory-instance.jfrog.io
  ARTIFACTORY_REGISTRY: ${{ secrets.JFROG_ARTIFACTORY_REGISTRY }}

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to JFrog Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ARTIFACTORY_REGISTRY }}
          username: ${{ secrets.JFROG_USERNAME }} # Your JFrog username (e.g., service account)
          password: ${{ secrets.JFROG_PASSWORD }} # Your JFrog password or API Key

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend Image
        id: docker_build_backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend # Path to your backend Dockerfile context
          file: ./backend/Dockerfile # Path to your backend Dockerfile
          push: true
          tags: |
            ${{ env.ARTIFACTORY_REGISTRY }}/iotgo-backend:${{ github.sha }}
            ${{ env.ARTIFACTORY_REGISTRY }}/iotgo-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-push-frontend:
    runs-on: ubuntu-latest
    needs: build-and-push-backend # Ensure backend is built first if frontend depends on it (optional, remove if not needed)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to JFrog Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ARTIFACTORY_REGISTRY }}
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Frontend Image
        id: docker_build_frontend
        uses: docker/build-push-action@v6
        with:
          context: ./react-frontend # Path to your frontend Dockerfile context
          file: ./react-frontend/Dockerfile # Path to your frontend Dockerfile
          push: true
          tags: |
            ${{ env.ARTIFACTORY_REGISTRY }}/iotgo-frontend:${{ github.sha }}
            ${{ env.ARTIFACTORY_REGISTRY }}/iotgo-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
